sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: Kk6lF1DcoX4+zNjKtkr0+iIqpip0/CWeT6vDW9KINaRVsIZzottqGeV4iGe+vOxFkEc9ufeE2GgKIRfgXvQT+6ESrjRsBxInIvqRRrJGQ2H1Mi9cljdBM+0pw6eOI4Ycwcy2owYVSWBCaipua6K0767StEwiJ47chcTcvmlAMvLQGPpo4I3yWc1OUTE4Kg7aB11a6yXT2jAOWQjjDq31Abc7blO6xKSs3RpXgAiqMz9VfqyoYmNuWQZKgjY1TnGRzkKKID/7mCE3TL/JXPQMJ3c+iIMZMJpAfUIhkRJW0QTwmIDx4ffqmfDOkaLfOkpdqHARQolDnF2TrQ7gC5hFhmOXP/CKILmRYrJrjccfjwcBq3H0dSOiAAHFrEOdL+KqU28edpZhN5MPKPismil0A8g4on1A7qecD79MRejDC8/F1oXnOLT7BLD/5hQzopnnm0Ud7HQPHcF3nnQeoxhgJXsqH7FVWZubf7AT43cBqXcKCL7IcovQNtiTxYAaJDGlT+fwJgCrgna9sikdhTjPKEnCtMWSQLuaQXPxqAIAGCfZN7LyWasLdkp3U9paczpy1S8srWDLz4VrrykSh3KzkEGNqdle45p30QwU5TvO9e1SuFYyw8NNPRKLqf6kKUyLUv7pkCQvsrm5o1oQmntmU2TMnCn/S8j4xGXFqwIrr2s=
branches:
  only:
  - jekyll
deploy:
    provider: pages
    local-dir: ./_site
    target-branch: master
    github-token: $GITHUB_TOKEN
